### ISSUE TITLE
Code in chapter 08 doesn't work

### ISSUE THREAD

**Issue by brevelles** [PacktPublishing/MEAN-Web-Development#2]
Cloning the code from chapter 08, installing the packages and starting the mongod service doesn't seem to run the app. The browser displays the text:

**App loading...**

console output:
systemjs.config.js:1 Uncaught SyntaxError: Unexpected token <

Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	Evaluating http://localhost:3000/app
	Error loading http://localhost:3000/app
	    at eval (<anonymous>)
	Evaluating http://localhost:3000/app
	Error loading http://localhost:3000/app

**Comment by AurobindoKar** [comment]
Hi,

I am closing the issue.
In case the issue still persists, feel free to reopen it.

Thanks
