### ISSUE TITLE
Missing file "systemjs.config.js"

### ISSUE THREAD

**Issue by clever98** [PacktPublishing/MEAN-Web-Development#3]
I think you maybe missed adding systemjs.config.js file.
All code from chapter 7 doesn't run.

**Comment by bhofmei** [comment]
Agreed! Please fix! I've spent hours trying to find an error in my own code going through the book and the bug seems to be in this file.

**Comment by a951racer** [comment]
I changed my index.ejs:

change this:

<script src="systemjs.config.js"></script>

to this:

<script src="system.config.js"></script>
