### ISSUE TITLE
Chapter 7 and 8 Code Does not Work!

### ISSUE THREAD

**Issue by debasisb** [PacktPublishing/MEAN-Web-Development#4]
Hi, I cloned the code from Chapter 7 and 8. Ran MongoD service but the code gives errors about Jasmine.

**Comment by edswartz** [comment]
I have a similar problem. Since the file was not present in this repository or from the publisher's site, I created a systemjs.config.js file inside of the public directory. I've tried to double check it and match it against what is in the book, but maybe I missed something: 

```
(function(global){
  var packages = {
    app: {
      main: './bootstrap.js',
      defaultExtensions: 'js'
    }
  };

  var map = {
    '@angular': 'lib/@angular',
    'rxjs': 'lib/rxjs'
  };

  var ngPackageNames = [
    'common',
    'compiler',
    'core',
    'forms',
    'http',
    'router',
    'platform-browser',
    'platform-browser-dynamic',
  ];

  ngPackageNames.forEach(function(pkgName){
    packages['@angular/' + pkgName] ={
      main: '/bundles/' +pkgName +'.umd.js',
      defaultExtensions: 'js'
    };
  });

  System.config({
    defaultExtensions:true,
    transpiler: null,
    packages: packages,
    map: map
  });
})(this);

```

The error I get is: 
```
Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	Evaluating http://localhost:3000/lib/rxjs/Subject
	Error loading http://localhost:3000/app/bootstrap.js
	    at eval (<anonymous>)
	Evaluating http://localhost:3000/lib/rxjs/Subject
	Error loading http://localhost:3000/app/bootstrap.js

```

**Comment by bgharper** [comment]
In systemjs.config.js, add rxjs under packages:
```
    var packages = {
        app: {
            main: './bootstrap.js',
            defaultExtension: 'js',
            format: 'register'
        },
        rxjs: {
            defaultExtension: 'js',
            main: 'Rx.js'
        }
    };
```
And make sure your systemjs version in `package.json` is the exact version in the book (0.19.39). 

This took me forever to figure out and is pretty annoying given that up until this point I was enjoying the book.

**Comment by edswartz** [comment]
Wow. That worked. Thank you!! On to new errors and to figure out why this worked :)

**Comment by bgharper** [comment]
Yeah it's definitely not an optimal solution since it pulls in all of rxjs (which means it takes forever to load). I'll update it with an explanation if I figure out something better :)

**Comment by a951racer** [comment]
I think the problem may actually be a typo in the index.ejs file.  I modified my index.ejs thusly:

change this:

<script src="systemjs.config.js"></script>

to this:

<script src="system.config.js"></script>

That cured the issue for me.  Of course that then exposed an issue with a deprecated syntax for routing....
