### ISSUE TITLE
Chapter 6 uses crypto.pbkdf2Sync needs additional parameter

### ISSUE THREAD

**Issue by Dima11235813** [PacktPublishing/MEAN-Web-Development#6]
It seems that the

return crypto.pbkdf2Sync(password, this.salt, 10000, 64).toString('base64');

call requires an additional parameter

it throws an error

crypto.js:694
    throw new TypeError(
    ^

TypeError: The "digest" argument is required and must not be undefined
    at pbkdf2 (crypto.js:694:11)

after finding 

https://stackoverflow.com/questions/44606054/typeerror-the-digest-argument-is-required-and-must-not-be-undefined

I added the digest string param 

return crypto.pbkdf2Sync(password, this.salt, 10000, 64, 'sha1').toString('base64');

and the error stopped, not 100% whether this is correct, just reading the book and learning so, please let me know if this solution is appropriate.

**Comment by githubce** [comment]
Hi @Dima11235813 

return crypto.pbkdf2Sync(password, this.salt, 10000, 64).toString('base64');

should be:

return crypto.pbkdf2Sync(password, this.salt, 10000, 64, 'sha512').toString('base64');

Regards,
