### ISSUE TITLE
Chapter 6 needs a promise library

### ISSUE THREAD

**Issue by Dima11235813** [PacktPublishing/MEAN-Web-Development#7]
It seems that there have been changes to how Mongoose is implemented

it now requires the addition of a promise provider

they recommend bluebird

this is the error message

GET /signup 304 13.046 ms - -
(node:18208) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Assignment to constant variable.

I added 

var promiseFromBluebird = require("bluebird");
mongoose.PromiseProvider = promiseFromBluebird;

and it works

is this how you would update this?

**Comment by Dima11235813** [comment]
https://stackoverflow.com/questions/40551550/what-is-the-correct-way-of-using-bluebird-for-mongoose-promises

This shows that 

var Promise = require("bluebird");
Promise.promisifyAll(require("mongoose"));

this is how it should be done

**Comment by ManikandanKurup-Packt** [comment]
Thank you for posting the workaround. Please reopen if the issue still persists
